config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  root to: "questions#index"

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end

  resources :questions, except: [:edit], concerns: :votable do
    resources :answers, only: [:create, :update, :destroy], shallow: true, concerns: :votable
    resources :comments, only: :create, defaults: { commentable: 'question' }
    resources :question_subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :answers, only: [] do
    resources :comments, only: :create, defaults: { commentable: 'answer' }
    patch :accept_as_best, on: :member
  end

  resources :attachments, only: [:destroy]

  resources :comments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :collection
  end

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Authorable
  include Attachable
  include Votable
  include Commentable

  scope :created_yesterday, -> { where(created_at: Time.zone.now.yesterday.all_day) }

  has_many :answers, dependent: :destroy

  has_many :subscriptions, \
           foreign_key: 'question_id', \
           class_name: 'QuestionSubscription', \
           dependent: :delete_all

  has_many :subscribers, \
           through: :subscriptions, \
           source: :user

  validates :title, :body, presence: true

  after_create :subscribe_author

  def subscription_by(user)
    subscriptions.find_by(user: user)
  end

  private

  def subscribe_author
    subscribers << author
  end
end

app/controllers/api/v1/questions_controller.rb
module API
  module V1
    class QuestionsController < API::V1::BaseController
      before_action :load_resource, only: :show

      def index
        respond_with(@questions = Question.all)
      end

      def show
        respond_with @question
      end

      def create
        respond_with(@question = Question.create(resource_params))
      end

      private

      def permit_attributes
        [:title, :body]
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationThinController
  include VotableController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_resource, only: [:show, :update, :destroy]

  after_action :publish_changes, only: [:create, :destroy]

  authorize_resource

  respond_to :html, only: [:index, :show, :new, :create, :destroy]
  respond_to :js, only: [:create, :update, :destroy]

  def index
    respond_with(@questions = Question.all)
  end

  def show
    @subscription = @question.subscription_by current_user || QuestionSubscription.new
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = Question.create(resource_params))
  end

  def update
    @question.update resource_params
    respond_with @question
  end

  def destroy
    @question.destroy
    respond_with @question
  end

  private

  def include_resources
    case action_name
    when 'show'
      [:attachments, :votes, :comments, answers: [:attachments, :votes, :comments]]
    when 'update'
      [:attachments]
    else
      []
    end
  end

  def publish_channel
    "questions"
  end

  def permit_attributes
    [:title, :body, attachments_attributes: [:id, :file, :_destroy]]
  end
end

app/views/questions/_edit.html.slim
= nested_form_for @question, \
    remote: true, \
    html: { id: "form_edit_#{ dom_id @question }", style: "display: none" } \
    do |f|
  p
    = f.label :title
    br
    = f.text_field :title

  p
    = f.label :body
    br
    = f.text_area :body

  p = render 'attachments/form', form: f

  p
    = f.submit t('question.action.confirm.edit')

app/views/questions/_form.html.slim
= nested_form_for @question, remote: true, html: { id: "for_edit_#{ dom_id @question }", style: "display: none" } do |f|
  p
    = f.label :title
    br
    = f.text_field :title

  p
    = f.label :body
    br
    = f.text_area :body

  p = t 'attachments.label'
  p = render 'attachments/form', form: f

  p
    = f.submit t('question.action.confirm.edit')

app/views/questions/_index_item.html.slim
= div_for question
  span
    = link_to question.title, question_path(question)

  - if current_user_author_of? question
    =< render 'shared/link_delete', item: question

app/views/questions/_index_record.html.slim
= div_for question
  span
    = link_to question.title, question_path(question)

  - if can? :destroy, question
    =< render 'shared/link_delete', item: question

app/views/questions/_item.html.slim
= div_for question, :item
  h1
    = question.title
  p
    = question.body

  = render 'attachments/list', container: question

app/views/questions/_publish_create.js.erb
$(".questions").append('<%= j render 'questions/index_record', question: question %>')

app/views/questions/_publish_destroy.js.erb
$("#<%= dom_id question %>").remove()

app/views/questions/_question.html.slim
= div_for question

  = render 'item', question: question

  - if can? :modify, question

    = render 'edit', question: question

    = div_for @question, :links
      = render 'shared/link_edit', item: question
      =< render 'shared/link_delete', item: question, remote: false

  = render 'votes/show', votable: question

  = render 'comments/list', container: question

  hr

  = render 'answers/list', question: question

app/views/questions/destroy.js.erb
<%= render 'shared/remove_item_after_destroy', item: @question, published: true %>

app/views/questions/index.html.slim
.questions

  - @questions.each do |question|
    = render 'index_record', question: question

br
- if can? :create, Question
  = link_to t('question.action.new'), new_question_path

= subscribe_to "/questions"

app/views/questions/new.html.slim
= nested_form_for @question do |f|
  p
    = f.label :title
    br
    = f.text_field :title

  p
    = f.label :body
    br
    = f.text_area :body

  p = render 'attachments/form', form: f

  p = f.submit t 'question.action.confirm.new'

app/views/questions/show.html.slim
= render 'question_subscriptions/links', question: @question

= render @question

- if can? :create, Answer
  hr
  = render 'answers/new', question: @question

= subscribe_to "/questions/#{ @question.id }/answers"
= subscribe_to "/questions/#{ @question.id }/comments"

app/views/questions/update.js.erb
<%= render layout: 'shared/layouts/update_item_after_action', locals: { \
  item: @question, \
  action: :update \
} do %>
  $("#form_edit_<%= dom_id @question %>").hide()
  $("#link_edit_<%= dom_id @question %>").show()
  $("#item_<%= dom_id @question %>").replaceWith('<%= j render 'questions/item', question: @question %>');
<% end %>