config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  root to: "questions#index"

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end

  resources :questions, except: [:edit], concerns: :votable do
    resources :answers, only: [:create, :update, :destroy], shallow: true, concerns: :votable
    resources :comments, only: :create, defaults: { commentable: 'question' }
    resources :question_subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :answers, only: [] do
    resources :comments, only: :create, defaults: { commentable: 'answer' }
    patch :accept_as_best, on: :member
  end

  resources :attachments, only: [:destroy]

  resources :comments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :collection
  end

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/search.rb
class Search
  def self.search(query, option=nil)
    return [] unless query.present?

    escaped_query = Riddle::Query.escape(query)

    if indices.include? option.to_sym
      index_name = "#{ option }_core"
      ThinkingSphinx.search escaped_query, indices: [index_name]
    else
      ThinkingSphinx.search escaped_query
    end
  end

  def self.options_for_select
    search_options.invert.to_a
  end

  def self.search_options
    {
      question_with_associations: 'questions, including all associations',
      all: 'all objects',
      question: 'only questions',
      answer: 'only answers',
      comment: 'only comments',
      user: 'only users'
    }
  end

  def self.indices
    @indices ||= search_options.keys - [:all]
  end

  private_class_method :search_options, :indices
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  authorize_resource

  respond_to :html

  def search
    @results = Search.search(params[:query], params[:search_option])
    respond_with @results
  end
end

app/views/search/_answer_item.html.slim
strong Answer #{ answer.id }

= div_for answer, :item
  span.body = answer.body

hr

app/views/search/_comment_item.html.slim
strong Comment #{ comment.id }

= div_for comment, :item
  span.body = comment.body

hr

app/views/search/_form.html.slim
- if can? :search, Search

  div#search = form_tag search_path, method: 'get'
    = text_field_tag :query, params[:query]

    = select_tag(:search_option, \
      options_for_select(Search::options_for_select, \
      params[:search_option]))

    = submit_tag t('search.action.search')

app/views/search/_question_item.html.slim
strong = link_to "Question #{ question.id }", question_path(question)

= div_for question, :item
  span.title = question.title
  span.body  = question.body

hr

app/views/search/_user_item.html.slim
strong User #{ user.id }

= div_for user, :item
  span.user_name = user.user_name

hr

app/views/search/search.html.slim
h1 Search results

- if @results.any?
  - @results.each do |result|
    - resource_name = result.model_name.element
    = render "search/#{ resource_name }_item", \
      "#{ resource_name }": result

- else
  | Nothing was found