config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  root to: "questions#index"

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :withdraw_vote
    end
  end

  resources :questions, except: [:edit], concerns: :votable do
    resources :answers, only: [:create, :update, :destroy], shallow: true, concerns: :votable
    resources :comments, only: :create, defaults: { commentable: 'question' }
    resources :question_subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :answers, only: [] do
    resources :comments, only: :create, defaults: { commentable: 'answer' }
    patch :accept_as_best, on: :member
  end

  resources :attachments, only: [:destroy]

  resources :comments, only: [:destroy]

  resources :identities, only: :show do
    get :confirm, on: :collection
  end

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/views/layouts/_attachments.html.slim
- if container.attachments.any?

  .attachments
    - container.attachments.each do |attachment|

      div id="file_#{ attachment.id }"

        = link_to attachment.file_identifier, attachment.file.url

        - if user_signed_in? and (container.user_id == current_user.id)
          = link_to 'Delete file', file_path(attachment), method: :delete, id: "delete_file_#{ attachment.id }", remote: true

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackoverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<div><%= render 'search/form' %></div>

<%= yield %>

<br/><br/>
<div><%= link_to t('question.action.index'), questions_path %></div>

<div><%=
  if user_signed_in?
    link_to 'log out', destroy_user_session_path, method: :delete
  else
    link_to 'log in', new_user_session_path, method: :get
  end
%></div>
</body>
</html>